# Generated by Django 4.0.4 on 2022-05-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cripto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='', verbose_name='icono')),
                ('image', models.ImageField(null=True, upload_to='image/', verbose_name='imagen')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('sigle', models.CharField(max_length=100, verbose_name='siglas')),
                ('unids', models.CharField(max_length=100, null=True, verbose_name='unidades')),
                ('preci', models.CharField(max_length=100, verbose_name='precio')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='descripcion')),
                ('codeFont', models.CharField(max_length=100, verbose_name='codigoFuente')),
                ('web', models.CharField(max_length=100)),
            ],
        ),
    ]
